name: Build and Push Docker Image

on:
  push:
    branches:
      - snapshot
      - elephant
      - duck

env:
  DOCKER_REPO: docker.io/livebinders
  DOCKER_HUB_BUILD_NUMBER: ${{ vars.DOCKER_HUB_BUILD_NUMBER }} # Read from GitHub Secrets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Animal Variable (Branch Name)
        run: echo "ANIMAL=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: "this_repo"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true  # Runs `bundle install` automatically
        working-directory: this_repo

      - name: Verify Ruby and Bundler versions
        run: |
          ruby -v
          bundler -v
        working-directory: this_repo

      - name: Run script
        run: bundle exec ruby scripts/find_or_create_and_merge_pr.rb
        working-directory: this_repo

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: "livebinders/livebinders"  # Replace with the actual repo
          ref: ${{ env.ANIMAL }}
          path: "."
          token: ${{ secrets.PAT_TOKEN }}  # Required for private repos

      - name: Set Git Commit and Branch
        run: |
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Read Docker Hub Build Number
        run: echo "BUILD_TAG=${{ env.DOCKER_HUB_BUILD_NUMBER }}" >> $GITHUB_ENV

      - name: Generate build.yml
        run: |
          echo "---" > build.yml
          echo "GIT_COMMIT: $GIT_COMMIT" >> build.yml
          echo "GIT_BRANCH: $GIT_BRANCH" >> build.yml
          echo "BUILD_TAG: $BUILD_TAG" >> build.yml
          cat build.yml

      - name: Increment Docker Build Number
        run: echo "$((BUILD_TAG + 1))" > docker_hub_build_number.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build --file=./Dockerfile.lbapp \
            --tag=${{ env.DOCKER_REPO }}/${{ env.ANIMAL }}:latest \
            --tag=${{ env.DOCKER_REPO }}/${{ env.ANIMAL }}:$BUILD_TAG .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_REPO }}/${{ env.ANIMAL }}:$BUILD_TAG
          docker push ${{ env.DOCKER_REPO }}/${{ env.ANIMAL }}:latest

      - name: Save New Docker Build Number to GitHub Secret
        run: |
          NEW_BUILD_TAG=$(cat docker_hub_build_number.txt)
          echo "New Docker Build Number: $NEW_BUILD_TAG"
          curl -X PATCH -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/variables/DOCKER_HUB_BUILD_NUMBER \
               -d "{\"encrypted_value\":\"$NEW_BUILD_TAG\"}"

